<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <Copyright>Copyright © 2026 NetworkDLS</Copyright>
    <Version>2.4.1</Version>
    <Company>NetworkDLS</Company>
    <Product>NetProxy</Product>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="AppIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NTDLS.ReliableMessaging" Version="3.4.6" />
    <PackageReference Include="protobuf-net" Version="3.4.21" />
  </ItemGroup>

</Project>
